//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisSzachowy.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Users
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int ELO { get; set; }
        public int startedGames { get; set; }
        public int finishedGames { get; set; }
    }
    public class UsersDBContext : DbContext
    {
        public DbSet<Users> Movies { get; set; }
    }
}
